version: '3.8'

services:
  ecommerce:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads
      - ./logs:/logs
    environment:
      - FLASK_ENV=development
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
