version: "3.8"

services:
  cowrie:
    image: cowrie/cowrie
    ports:
      - "22:22"
      - "23:23"
      - "2222:2222"
      - "2323:2323"
    volumes:
      - ./cowrie-elastic-stack/cowrie/config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie-elastic-stack/cowrie/config/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ./cowrie-elastic-stack/cowrie/log/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
    networks:
      - elastic

  fake_web:
    build:
      context: ./fake_web
    ports:
      - "5000:5000"
    volumes:
      - ./fake_web/uploads:/uploads
      - ./fake_web/logs:/fake_web/logs
    environment:
      - FLASK_ENV=development
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
    networks:
      - elastic

  elasticsearch:
    build: ./cowrie-elastic-stack/elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    volumes:
      - ./cowrie-elastic-stack/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    build: ./cowrie-elastic-stack/kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    build: ./cowrie-elastic-stack/logstash
    ports:
      - "5044:5044"
    volumes: 
      - ./cowrie-elastic-stack/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./cowrie-elastic-stack/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
    build: ./cowrie-elastic-stack/filebeat
    volumes:
      - ./cowrie-elastic-stack/cowrie/log/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
      - ./cowrie-elastic-stack/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
    networks:
      - elastic

  dashboard:
    image: nginx:latest
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - elastic

volumes:
  elasticsearch:

networks:
  elastic:
    driver: bridge
